EARTH_SEMI_MAJOR_AXIS = 6378136
EARTH_SEMI_MINOR_AXIS = EARTH_SEMI_MAJOR_AXIS * (1 - (1/298.25642))

EARTH_ECCENTRICITY    = (EARTH_SEMI_MAJOR_AXIS - EARTH_SEMI_MINOR_AXIS) / EARTH_SEMI_MAJOR_AXIS
EARTH_ECCENTRICITY2   = (EARTH_SEMI_MAJOR_AXIS - EARTH_SEMI_MINOR_AXIS) / EARTH_SEMI_MINOR_AXIS